she_codes_news/news/urls.py
from django.urls import path
from . import views
from .views import UpdateStoryView
from .views import DeleteStoryView
from .views import ViewAuthorView
from .views import AddCommentView


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('update-story/<int:pk>/', views.UpdateStoryView.as_view(), name='updateStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('view-author/<int:pk>/', ViewAuthorView.as_view(), name='viewAuthor'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='addComment'),
    # path('delete-success/<int:pk>/', DeleteSuccessView.as_view(), name='deleteSuccess'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import AuthorProfileView
from .views import UpdateProfileView

app_name = 'users'

urlpatterns = [
      path('create-account/', CreateAccountView.as_view(), name='createAccount'),
      path('author-profile/', AuthorProfileView.as_view(), name='authorProfile'),
      path('update-profile/', UpdateProfileView.as_view(), name='updateProfile'),
]

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    first_name = models.CharField(("first name"), max_length=150, blank=True)
    last_name = models.CharField(("last name"), max_length=150, blank=True)
    birth_date = models.DateField(null=True)
    profile_photo = models.URLField(null=True, blank=True)
    bio = models.TextField(null=True, max_length=200)

    def __str__(self):
        return self.username
    

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'birth_date','username', 'email', 'profile_photo', 'bio']
        widgets = {
            'birth_date': forms.DateInput(
                format='%m/%d/%Y',
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            )
        }
        # labels = {
        #     'profile_photo': 'Image URL'
        # }


class CustomUserChangeForm(UserChangeForm):   
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'birth_date', 'username', 'email', 'profile_photo', 'bio']

she_codes_news/users/views.py
from typing import Any
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from news.models import NewsStory

from .forms import CustomUserCreationForm
from .forms import CustomUserChangeForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class AuthorProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/authorProfile.html'
    context_object_name = 'authorprofile'

    def get_object(self, *args, **kwargs):
        return self.request.user
    
    # getting all user stories
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_stories'] = NewsStory.objects.filter(author=self.request.user).order_by('-pub_date')
        return context
    
class UpdateProfileView(generic.UpdateView):
    model = CustomUser
    template_name = 'users/updateProfile.html'
    fields = ['first_name', 'last_name', 'birth_date','username', 'email', 'profile_photo', 'bio']

    def get_object(self, *args, **kwargs):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('users:authorProfile')

# If have time have a view to delete profile

she_codes_news/users/templates/users/authorProfile.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %} 

    {% if request.user.is_authenticated %}
        <section class="author-profile">
            <h2>Hello, {{ user.username }}!</h2> 
            <div class="author-photo">
                {% if user.profile_photo %}
                    <img src="{{ user.profile_photo }}">
                {% else %}
                    <img src="{% static '/news/images/placeholder-5.jpg' %}">
                {% endif %}
            </div>
            <div>
                <h3>{{ user.first_name }} {{ user.last_name }}</h3>
                <p>DOB: {{ user.birth_date }}</p>
                <p>Email: {{ user.email }}</p>
                <p>Bio: {{ user.bio }}</p>
            </div> 
            <div class="button">
                <a href="{% url 'users:updateProfile' %}">Update</a>
            </div>
        </section>
        <br>
        <div class="stories-list">
            <h3>Your Stories</h3>
            <br>
            {% for story in user_stories %}
                {% if story.image %}
                    <img src="{{ story.image }}">
                {% else %}
                    <img src="{% static '/news/images/placeholder-5.jpg' %}">
                {% endif %}
                <a href="{% url 'news:story' story.id %}"><h3>{{ story.title }}</h3></a>
                <h5>{{ story.pub_date }}</h5>
            {% endfor %}
        </div>
    {% else %}
        <p> You are not authenticated. </p>
    {% endif %}

{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/styles.css' %}">
{% endblock %}

{% block content %} 
    <h2>Create Account</h2> 
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    </form>
{% endblock %}

she_codes_news/users/templates/users/updateProfile.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}