she_codes_news/news/urls.py
from django.urls import path
from . import views
from .views import UpdateStoryView
from .views import DeleteStoryView
from .views import ViewAuthorView
from .views import AddCommentView


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('update-story/<int:pk>/', views.UpdateStoryView.as_view(), name='updateStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('view-author/<int:pk>/', ViewAuthorView.as_view(), name='viewAuthor'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='addComment'),
    # path('delete-success/<int:pk>/', DeleteSuccessView.as_view(), name='deleteSuccess'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView
from .views import AuthorProfileView
from .views import UpdateProfileView

app_name = 'users'

urlpatterns = [
      path('create-account/', CreateAccountView.as_view(), name='createAccount'),
      path('author-profile/', AuthorProfileView.as_view(), name='authorProfile'),
      path('update-profile/', UpdateProfileView.as_view(), name='updateProfile'),
]

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Coders News</title>
        <meta name="description" content="">
        <meta name="author" content="YOUR NAME HERE">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1><span class="emphasis">{</span>Coders<span class="emphasis">}</span> News</h1>
                    <h4 id="slogan"> TV News while you code...</h4>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>
        <!-- include block content here -->
        {% block content %}{% endblock %}
    </body>
    <footer>
        <p id="footer">© <span class="emphasis">{</span>Coders<span class="emphasis">}</span> News</p>
    </footer>
</html>

she_codes_news/templates/nav.html
<nav>
    <!-- Home button is not needed -->
    <!-- <a href="{% url 'news:index' %}">Home</a> -->
    {% if request.user.is_authenticated %}
        <h4 id="nav-name">Hi, {{ user.first_name }}</h4>
        <br>
        <a href="{% url 'users:authorProfile' %}" class="nav-links">My Profile</a>
        <a href="{% url 'news:newStory' %}" class="nav-links">Add Story</a>
        <a href="{% url 'logout' %}" id="log-function" class="nav-links">Logout</a>
    {% else %}
        <a href="{% url 'login' %}" class="nav-links">Login</a>
        <a href="{% url 'users:createAccount' %}" class="nav-links">Create Account </a>
    {% endif %}
</nav>

<!-- <span class="emphasis">{{ user.first_name }}!</span> -->