she_codes_news/news/urls.py
from django.urls import path
from . import views
from .views import UpdateStoryView
from .views import DeleteStoryView
from .views import ViewAuthorView
from .views import AddCommentView


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('update-story/<int:pk>/', views.UpdateStoryView.as_view(), name='updateStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('view-author/<int:pk>/', ViewAuthorView.as_view(), name='viewAuthor'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='addComment'),
    # path('delete-success/<int:pk>/', DeleteSuccessView.as_view(), name='deleteSuccess'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.forms import ModelForm



class NewsStory(models.Model):
    Categories = [
        ('Animals', 'Animals'),
        ('Travel', 'Travel'),
        ('Food', 'Food'),
        ('World', 'World'),
        ('Sport', 'Sport'),
        ('Lifestyle', 'Lifestyle'),
        ('Entertainment', 'Entertainment'),
        ('Technology', 'Technology')
    ]

    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    category = models.CharField(max_length=15, blank=False, choices=Categories, default="")
    pub_date = models.DateField()
    content = models.TextField()
    image = models.URLField(null=True, blank=True)

class Comment(models.Model):
    story = models.ForeignKey(NewsStory, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments')  
    content = models.TextField()
    created = models.DateField(auto_now_add=True)
    modified_date = models.DateField(auto_now=True)

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory
from .models import Comment

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'category', 'image', 'content' ]
        widgets = {
            'pub_date': forms.DateInput(
                format='%m/%d/%Y',
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            ),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    #     widgets = {
    #     'content': forms.TextInput(attrs={'class': 'hidden-label'}),
    # }

she_codes_news/news/views.py
from typing import Any
from django.db import models
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import NewsStory, Comment
from .forms import StoryForm, CommentForm
from django.shortcuts import render, get_object_or_404, redirect
from users.models import CustomUser
from .forms import CommentForm

class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['form'] = CommentForm()
        return context

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class UpdateStoryView(generic.UpdateView):
    model = NewsStory
    template_name = 'news/updateStory.html'
    fields = ['title', 'category', 'image', 'content']

    def get_success_url(self):
        return reverse_lazy('news:story', kwargs={'pk': self.object.pk})
    
    # stop someone going through url to update a story that is not theirs
    def form_valid(self, form):
        if form.instance.author == self.request.user:
            return super().form_valid(form)

# Function based view to confirm delete success
# def DeleteSuccessView(request):
#     return render(request, 'news/deleteSuccess.html')

class DeleteStoryView(generic.DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')
    context_object_name = 'deletestory'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['story'] = NewsStory.objects.get(id=self.kwargs['pk'])
        return context

class ViewAuthorView(generic.DetailView):
    model = CustomUser
    template_name = 'news/viewAuthor.html'
    context_object_name = 'viewAuthor'

    def get_object(self, *args, **kwargs):
        return CustomUser.objects.get(pk=self.kwargs['pk'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author_id = self.kwargs['pk']

        # get the author's stories
        context['all_stories'] = NewsStory.objects.filter(author_id=author_id)
        context['author'] = CustomUser.objects.get(id=self.kwargs['pk'])
        return context
    
class AddCommentView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'news/story.html'
    context_object_name = 'comments'

    def get(self, request, *args, **kwargs):
        return redirect("news:story", pk=self.kwargs.get("pk"))

    def form_valid(self, form):
        form.instance.author = self.request.user
        pk = self.kwargs.get("pk")
        story = get_object_or_404(NewsStory, pk=pk)
        form.instance.story = story
        response = super().form_valid(form)
        return response
    
    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse('news:story', kwargs={'pk': pk})

# If i have time do delete comment view

# class DeleteCommentView(generic.DeleteView):
#     model = Comment
#     template_name = 'news/story.html'
#     # success_url = reverse_lazy('news:index')
#     context_object_name = 'deletecomment'

she_codes_news/news/templates/news/addComment.html
<!-- {% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div>
        <h2>Add comment</h2>
    <form id="comment-form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if request.user.is_authenticated %}
        <input class="submit-button" type="submit" value="Submit">
        {% else %}
        <p class="warning-label">log in to comment on stories.</p>
        <a class="log-button" href="{% url 'login' %}">Login</a>
        {% endif %}
    </form>
    </div>
{% endblock %} -->

<!-- NOT BEING USED ANYMORE ?-->

she_codes_news/news/templates/news/commentCard.html
<section class="comment-card">
    <p>{{ comment.content }}</p>
    <p class="comment"> - {{ comment.author }}</p>
    <p class="comment">{{ comment.created }}</p>    
</section>

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %} 
<section id="delete-story">
    {% if request.user == story.author %}
        <h2>Hello {{ user.username }}!</h2> 
        <p>Are you sure you would like to delete {{ story.title }}</p>
        <div class="delete-buttons">
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Yes">
        </form>
        <a href="{% url 'news:story' story.id %}" class="button">No</a>
        </div>
    {% else %}
        <p> You are not authenticated </p>
    {% endif %}
</section>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<br>
    <h2>Latest News</h2>
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
    <br>
    <h2>All Stories</h2>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<section id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <a href="{% url 'news:viewAuthor' pk=story.author.pk %}"><h3 class="author-name">{{ story.author.username }}</h3></a>
    <p>{{ story.pub_date }}</p>
    <div id="story-content">
        {% if story.image %}
            <img src="{{ story.image }}">
        {% else %}
            <img src="{% static '/news/images/placeholder-5.jpg' %}">
        {% endif %}
    </div>
    <div class="story-text">{{ story.content|linebreaks }}</div> 
</section>
<section>
    {% if request.user.is_authenticated %}
        {% if request.user == story.author %}
      
            <a href="{% url 'news:updateStory' story.id %}" class="button">Update</a>
      
          
            <a href="{% url 'news:deleteStory' story.id %}" class="button">Delete</a>
            
        {% endif %}
    {% endif %}
</section>
<br>
<!-- show comments -->
<section>
    <h3 id="comment-wrapper">Comments</h3>
    {% if story.comments.count %}
        {% for comment in story.comments.all %}
            {% include "./commentCard.html" with comment=comment %}
        {% endfor %}
    {% else %}
    <p>No comments yet.</p>
    {% endif %}
</section>

<div>
    {% if request.user.is_authenticated %}
    <h4>Leave a comment</h4>
        <form id="comment-form" method="post" action="{% url 'news:addComment' story.id %}" >
                {% csrf_token %}
                {{ form.as_p }}
        <input class="submit-button" type="submit" value="Add Comment">
    {% else %}
        <a href="{% url 'login' %}">log in to comment on stories</a>
        <!-- Style as button -->
    {% endif %}
    </form>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image %}
            <img class= story_image src="{{ story.image }}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3 id="story-title">{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h5>{{ story.pub_date }}</h5>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/updateStory.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

she_codes_news/news/templates/news/viewAuthor.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %} 
    <section class="view-author">
        <h2> {{ author.username }} </h2> 
        <div class="author-photo">
            {% if author.profile_photo %}
                <img src="{{ author.profile_photo }}">
            {% else %}
                <img src="{% static '/news/images/placeholder-5.jpg' %}">
            {% endif %}
        </div>
        <div>
            <h3>{{ author.first_name }} {{ author.last_name }}</h3>
            <p>Bio: {{ author.bio }}</p>
        </div>  
    </section>
    
    <br>
    <div class="stories-list">
        <h3> View {{ author.username }}'s stories </h3>
        {% for story in all_stories %}
            {% if story.image %}
                <img src="{{ story.image }}">
            {% else %}
                <img src="{% static '/news/images/placeholder-5.jpg' %}">
            {% endif %}
            <a href="{% url 'news:story' story.id %}"><h3>{{ story.title }}</h3></a>
            <h5>{{ story.pub_date }}</h5>
        {% endfor %}
    </div>
    
{% endblock %}